parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    homeapp.api_response.listener:
        class: Homeapp\ExchangeBundle\Listener\ApiResponseListener
        arguments:
            - '@jms_serializer.serializer'
        tags:
            - { name: kernel.event_listener, event: kernel.view }
            - { name: kernel.event_listener, event: kernel.exception }

    homeapp.serializer.identical_naming_strategy:
        class: Homeapp\ExchangeBundle\Serializer\IdenticalStrategy
